event/urls.py
from django.urls import path
from . import views

app_name='event'

urlpatterns = [
    path('', views.index, name = "index"),
    path('all-events/', views.all_events, name = "all-events"),
    path('create-event/', views.create_event, name = "create-event"),
    path('sort-event/', views.TimingListView.as_view(), name = "sort-event"),
    path('event-detail/<int:pk>', views.EventDetail.as_view(), name="event-detail"),
    path('edit-event/<int:pk>', views.edit_event, name = "edit-event"),
]

eventApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('event.urls')),
    path('', include('places.urls')),
]
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

places/urls.py
from django.urls import path
from . import views

app_name = 'places'

urlpatterns = [
    path('', views.index, name = "index"),
    path('all_places', views.PlacesListView.as_view(), name="all_places"),
    path('sort_by_city', views.sortCity, name="sort_by_city"),
    path('all_places/<int:pk>', views.PlacesDetailView.as_view(), name = "place-detail"),
]

#  Update url for adding new place

urlpatterns += [
    path('add_place', views.add_place, name="add_place"),
]

# Update url for adding distinct cities

urlpatterns += [
    path('distinct_cities/<str:cityname>', views.all_place_in_city, name="instance-city-place"),
]

event/models.py
from django.db import models
from taggit.managers import TaggableManager
from places.models import Place
from django.contrib.auth.models import User

from model_utils.models import TimeStampedModel
# from datetime import datetime, timedelta


TAGGIT_CASE_INSENSITIVE = True

class Event(TimeStampedModel):
    title = models.CharField(max_length=200)
    place = models.ForeignKey(Place, default=None, on_delete=models.CASCADE)
    tags = TaggableManager()
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title
    


class EventTime(models.Model):
    event_date = models.DateField(null=True)
    event_time = models.TimeField(null=True)
    event = models.ForeignKey('Event', on_delete=models.CASCADE)

    def __str__(self):
        return '{} {}'.format(self.event_time, self.event_date)


    

places/models.py
from django.db import models
from django.contrib.gis.db.models import PointField
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Place(models.Model):
    name = models.CharField(max_length=100)
    location = PointField(default=None)
    description = models.TextField(max_length=3000)
    address = models.CharField(max_length=500)
    city = models.CharField(max_length=100)
    type_of_place = models.CharField(max_length=100)

    def get_absolute_url(self):
        # pass
        return reverse('place-detail', args=[str(self.id)])

    def __str__(self):
        return self.name

event/forms.py
from django import forms
from django.contrib.gis import forms
from leaflet.forms.widgets import LeafletWidget
from .models import Event, EventTime


class EventForm(forms.ModelForm):
	class Meta:
		model = Event
		fields = (
            'title',
            'place',
            'tags',
            )
        # widgets = {'place':LeafletWidget()}

class EventTimeForm(forms.ModelForm):
    class Meta:
        model = EventTime
        fields = (
            'event_date',
            'event_time',
        )

places/forms.py
from django.contrib.gis import forms
from .models import Place
from leaflet.forms.widgets import LeafletWidget
from django import forms

class PlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = (
            'name', 
            'location',
            'description', 
            'address', 
            'city',
            'type_of_place',
            
            )
        widgets = {'location' : LeafletWidget()}

event/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from .models import Event, EventTime
from .forms import EventForm, EventTimeForm
from django.forms import formset_factory
from places.models import Place
from django.views.generic import DetailView, ListView
from django.contrib.auth import login, authenticate
from django.contrib import messages
from .models import Event
from .filters import EventFilters
# from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required

# Create your views here.


def index(request):
    return render(request, 'index.html')


def all_events(request):
    event_list = Event.objects.all()

    context = {
        'event_list' : event_list,
    }
    return render(request, 'event/all_events.html', context=context)

@login_required
def create_event(request):
    event_form = EventForm(request.POST or None)

    EventTimeFormSet = formset_factory(EventTimeForm, extra=1)
    event_time_form = EventTimeFormSet(request.POST or None)
    
    if event_form.is_valid() and event_time_form.is_valid():
        event_obj = event_form.save()
        event_obj.created_by = request.user
        event_obj.save()
        
        for event_time in event_time_form:
            event_time = event_time.save(commit = False)
            event_time.event = event_obj
            event_time.save()
            messages.success(request, 'Event created successfully.')
        return redirect('event:index')
    
    context = {
        'event_form' : event_form,
        'event_time_form' : event_time_form,
    }



    return render(request, 'event/add_event.html', context=context)

class TimingListView(ListView):
    model = EventTime
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = EventFilters(self.request.GET, queryset=self.get_queryset())
        return context

class EventDetail(DetailView):
    model = Event

@login_required
def edit_event(request, pk):
    event_obj = get_object_or_404(Event, id=pk)
    event_time_obj = get_object_or_404(EventTime, id=event_obj.id)

    if event_obj.created_by != request.user:
        messages.warning(request, 'You Cannot edit this event as you are not the one who created it.')
        return redirect('event:event-detail', pk)

    event_form = EventForm(request.POST or None, instance=event_obj)
    event_time_form = EventTimeForm(request.POST or None, instance=event_time_obj)

    if event_form.is_valid() and event_time_form.is_valid():
        event_instance = event_form.save()
        event_instance.created_by = request.user
        event_instance.save()
        event_time_form.save()
        messages.success(request, 'Event edited successfully.')
        return redirect('event:index')
    
    context = {
        # 'event_obj' : event_obj,
        'event_form' : event_form,
        # 'event_time_obj' : event_time_obj,
        'event_time_form' : event_time_form,
    }
    return render(request, 'event/add_event.html', context)

    
    

places/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import generic
from .forms import PlaceForm
from django.contrib import messages
# Create your views here.

from places.models import Place

def index(request):
    return render(request, 'index.html')

def sortCity(request):
    distinct_cities = Place.objects.distinct('city')
    return render(request, 'places/sortcity.html', context={'distinct_cities' : distinct_cities})

def all_place_in_city(request, cityname):
    list_of_place = Place.objects.filter(city=cityname)
    return render(request, 'places/sorted_by_city.html', context={'list_of_place' : list_of_place})



def add_place(request):
    if request.method == 'POST':
        form = PlaceForm(request.POST)
        
        if form.is_valid():
            x = form.save(commit=False)
            x.save()
            messages.success(request, 'Place added successfully.')
            return redirect('event:create-event')
    else:
        form = PlaceForm()
    
    return render(request, 'places/add_place.html', {"form":form})

class PlacesListView(generic.ListView):
    model = Place


class PlacesDetailView(generic.DetailView):
    model = Place

event/templates/base_generic.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Events | {% block title %}{% endblock title %} </title>
  </head>
  <body>
  {% comment %} NavBar code START {% endcomment %}

<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="{% url 'event:index' %}">EventApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'event:all-events' %}">All Events <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'event:create-event' %}">Create Event</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'event:sort-event' %}">Sort Events</a>
      </li> 
    </ul>
      {% if user.is_authenticated %}
        <li class = "nav-link" style="list-style-type:none;">Hi, {{ user.get_username }}</li>
        <a href="{% url 'logout'%}?next={{request.path}}" class="text-secondary">
          <button type="button" class="btn btn-outline-dark">Logout</button>
        </a>
      {% else %}
        <a href="{% url 'login' %}?next={{request.path}}" class="text-secondary">
          <button type="button" class="btn btn-outline-dark">Login</button>
        </a>
      {% endif %}
  </div>
</nav>

{% comment %}  {% endcomment %}
          
          
          {% comment %} <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
          
          <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li> {% endcomment %}
          
{% comment %}  {% endcomment %}

{% comment %} NavBar code END {% endcomment %}

{% comment %} Displaying messages if any START {% endcomment %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show my-0" role="alert">
  {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
{% endif %}
{% comment %} Displaying messsages if any END {% endcomment %}


    {% block content %}
    
    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  </body>
</html>

event/templates/event/add_event.html
{% extends 'base_generic.html' %}

{% load crispy_forms_tags %}

{% block title %}Add Event{% endblock title %}

{% block content %}

{% load leaflet_tags %}

{% leaflet_js plugins="forms" %}
{% leaflet_css plugins="forms" %}

<div class="container mx-auto">

<form  method="POST">
    {% csrf_token %}
    {{event_form|crispy}}

    {{event_time_form|crispy}}
    <div class="container text-center"> 
    <a href="{% url 'places:add_place' %}">
        <button type="button" class="btn btn-outline-dark mx-4">Add a New Place</button>
    </a>
    <button type="submit" class="btn btn-outline-dark mx-4">Add Event</button>
    <button type="reset" value="Reset" class="btn btn-outline-dark mx-4">Reset</button>
    </div>
  </form>

</div>


{% endblock content %}

event/templates/event/all_events.html
{% extends 'base_generic.html' %}

{% block title %}All Events{% endblock title %}

{% block content %}

{% comment %} All Events START {% endcomment %}

<div class="album py-5 bg-light">
  <div class="container">

    <div class="row">
      {% for i in event_list %}
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <div class="container text-center">
            <text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ i.title }}</text>
          </div>
          <div class="card-body">
            <div class="d-flex justify-content-between align-items-center">
              <div class="container text-center">
                <a href="{% url 'event:event-detail' i.id %}" class="text-decoration-none">
                  <button type="button" class="btn btn-sm btn-block btn-outline-secondary">View</button>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>

{% comment %} All Events END {% endcomment %}

{% endblock content %}

event/templates/event/event_detail.html
{% extends 'base_generic.html' %}

{% block title %} Event Detail {% endblock title %}

{% block content %}

<div class="container mx-auto" style="width: 1000px;">

    <h1 class="mt-4 px-5"> Event Name : {{event.title}}</h1>

    <h4 class="px-5"> Place : {{ event.place }}</h4>
    
    <h4 class="px-5">Tags :</h4>
    <div class="container px-5">
        <ul class="px-5">
            {% for tag in event.tags.all %}
                <h5><li class="px-4"style="list-style-type:none;">{{ tag }} </li></h5>
            {% endfor %}
        </ul>
    </div>
    
    
    <h4 class="px-5">created-by : {{ event.created_by }}</h4>
{% comment %} {{ event.eventtime_set.all }} {% endcomment %}
    <h4 class="px-5">Time :</h4>
    <ul class="px-5">
    {% for time in event.eventtime_set.all %}
        <h5><li class="px-4" style="list-style-type:none;"> {{ time }}</li> </h5>    
    
    {% endfor %}
</ul>

</div>

<div class="container text-center px-5 mt-5">
    <a href="{% url 'event:all-events' %}" class="text-decoration-none">
      <button type="button" class="btn btn-sm btn-outline-secondary">Back</button>
    </a>
    <a href="{% url 'event:edit-event' event.id %}" class="text-decoration-none">
      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
    </a>
  </div>



{% endblock content %}

event/templates/event/eventtime_list.html
{% extends 'base_generic.html' %}

{% block title %}Sort Event{% endblock title %}

{% block content %}

<div class="container mx-auto">
    <div class="row container mx-auto" style="width: 430px;">
        <div class="col">
            <div class="card card-body">
    
                <form method="GET">
                    {{ filter.form }}
    
                <button class="btn btn-primary" type="submit">Search</button>
              </form>
    
            </div>
        </div>
        
    </div>
    <hr>
    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Event Title</th>
            <th scope="col">Event Date</th>
            <th scope="col">Event Time</th>
          </tr>
        </thead>
        <tbody>
            {% for eventtime in filter.qs %}
          <tr>
            <th scope="row"> <a href="{% url 'event:event-detail' pk=eventtime.event.pk %}" class="text-decoration-none"> {{ eventtime.event }} </a> </th>
            <td>{{ eventtime.event_date }}</td>
            <td>{{ eventtime.event_time }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>




</div>



{% endblock content %}

<!-- {% for timing in filter.qs %}
        <tr>
            <td>{{timing.event}}</td>
            <td>{{timing.event_date}}</td>
            <td>{{timing.event_time}}</td>
            <td><a href="{% url 'event:event-detail' pk=timing.event.pk %}"><button type="button" class="btn btn-primary">Detail</button></a></td>
        </tr>
        {% endfor %} -->

event/templates/index.html
{% extends 'base_generic.html' %}


{% block title %}
Home Page
{% endblock title %}

{% block content %}

{% comment %} Corousal START {% endcomment %}

<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active" data-interval="2000">
      <img src="https://source.unsplash.com/1440x600/?nature,water" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <p>“To achieve great things, two things are needed: a plan and not quite enough time.” </p>
        <h5>-Leonard Bernstein</h5>
      </div>
    </div>
    <div class="carousel-item" data-interval="2000">
      <img src="https://source.unsplash.com/1440x600/?winter,ice" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <p>"Some people look for a beautiful place. Others make a place beautiful.” </p>
        <h5>-Hazrat Inavat Khan</h5>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>



{% comment %} Corousal END {% endcomment %}


{% endblock content %}

places/templates/base_generic.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    {% block title %}<title>Beautiful Places</title>{% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{%url 'index'%}">PlaceApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{%url 'places:index'%}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'places:all_places'%}">All Places <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{%url 'places:add_place'%}">Add New Place <span class="sr-only">(current)</span></a>
      </li>
    
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Filter
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{%url 'places:sort_by_city'%}">Based on Cities</a>
        </div>
      </li>
    </ul>
  </div>
</nav>


{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show my-0" role="alert">
  {{ message }}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endfor %}
{% endif %}

    {% block content %}
    
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  </body>
</html>

places/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://source.unsplash.com/1400x500/?temple,nature" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://source.unsplash.com/1400x500/?nature,temple" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://source.unsplash.com/1400x500/?tourist,mountain" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
{% endblock %}

places/templates/places/add_place.html
{% extends 'base_generic.html' %}
{% load crispy_forms_tags %}

{% block title %}Add Place{% endblock title %}


{% block content %}

{% load leaflet_tags %}
{% leaflet_js plugins="forms" %}
{% leaflet_css plugins="forms" %}

<div class="container">
<h4>Add a new place:</h4>

  <form  method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <div class="container text-center">
    <button type="submit" class="btn btn-outline-dark">Add Place</button>
    </div>
  </form>

</div>





{% endblock %}

places/templates/places/place_detail.html
{% extends "base_generic.html" %}


{%block content%}

{% load leaflet_tags %}
{% leaflet_css %}
{% leaflet_js %}

<h1 class="text-center"> {{place.name}} </h1>
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://source.unsplash.com/900x300/?{{place.name}}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://source.unsplash.com/900x300/?{{place.name}}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://source.unsplash.com/900x300/?{{place.name}}" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

{% comment %} Description and location side by side START {% endcomment %}

<div class="row mb-2">
    <div class="col-md-6">
      <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary">Description</strong>
          <p class="card-text mb-auto">{{place.description}}</p>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-success">Location</strong>
          {% comment %} <p class="card-text mb-auto">{{place.location}}</p> {% endcomment %}
          {% leaflet_map "main" callback="map_init" %}
        </div>
      </div>
    </div>
  </div>

{% comment %} Description and location side by side END {% endcomment %}

<div class="container text-center">
<p>Address: {{place.address}} </p>
<p>City : {{place.city}} </p>
<p>Type of Place : {{place.type_of_place}}</p> 
</div>

{% comment %} Map Rendering {% endcomment %}

<script type="text/javascript">
    function map_init(map, options) {
        // get point lat and lon
        var lon = "{{ place.location.x }}";
        var lat = "{{ place.location.y }}";

        // zoom to point & add it to map
        map.setView([lat, lon], 12);
        L.marker([lat, lon]).addTo(map);
    }
</script>

{%endblock%}

places/templates/places/place_list.html
{% extends "base_generic.html" %}

{%block content%}
<h1>All Places</h1>
  {% if place_list %}
  <ul>
    {% for place in place_list %}
      <li>
        {% comment %} <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}}) {% endcomment %}
        <a href="{{ place.get_absolute_url }}">{{ place.name }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no places to view. Please add some places</p>
  {% endif %} 
{%endblock%}

places/templates/places/sortcity.html
{% extends "base_generic.html" %}

{% block content%}
<h3> List of Cities to Select From: </h3>
 <div class="container my-4">
    <ul>
        {% for place in distinct_cities %}
        <li class="my-4">
            <a href="{% url 'instance-city-place' place.city %}">{{place.city}}</a>
        </li>
        {% endfor %}
    </ul>
  </div>
{% endblock%}

places/templates/places/sorted_by_city.html
{% extends 'base_generic.html' %}

{% block content %}


<div class="container">
    <ul>
        {% for place in list_of_place %}
        <li>
            <a href="{% url 'place-detail' place.pk %}">{{place}}</a>
        </li>

        {% endfor %}
    </ul>
</div>

{% endblock %}